site_name: COMP423 Course Notes
plugins:
  - search
  - mkdocs-material
theme:
  name: 'material'
  custom_dir: 'overrides'

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition

