site_name: COMP423 Course Notes
plugins:
  - search
  - mkdocs-material
theme:
<<<<<<< HEAD
  name: 'material'
  custom_dir: 'overrides'

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition

=======
  name: material

markdown_extensions:
  - pymdownx.superfences  # Enables code block syntax highlighting
  - admonition   
>>>>>>> 1965a8e637edb066bac762ed240a518d7de4f8f5
